### ISSUE TITLE
Vote fractions are overall, not task-specific

### ISSUE THREAD

**Issue by willettk** [CKrawczyk/gz_nodes_flask#3]
Is there an option to change the way the vote fractions are displayed? Right now, it shows the fraction of votes for a response divided by the total votes for the galaxy. The default for Galaxy Zoo data in the catalogs has been to show the vote fraction only compared to votes _for that task_. Is this something we could change (or at least have the ability to toggle)?

**Comment by CKrawczyk** [comment]
Adding this feature in now.  Both the total vote fraction and the vote fraction for the task will be shown on mouse over.

**Comment by willettk** [comment]
Great. Are changes automatically deployed to http://visualize.galaxyzoo.org ? I don't see both fractions there yet.

**Comment by CKrawczyk** [comment]
They are not, Adam will handle the re-deploy when he gets a chance.

**Comment by CKrawczyk** [comment]
The changes are live now.

**Comment by willettk** [comment]
Neat. Thanks, Coleman!
