### ISSUE TITLE
Redirect for URL

### ISSUE THREAD

**Issue by willettk** [CKrawczyk/gz_nodes_flask#4]
The current url for the site is http://visualize.galaxyzoo.org. Can we set up a redirect for http://visualise.galaxyzoo.org, for the significant fraction of our volunteers/science team that use British English?

Mentioning @astopy or whoever might be able to handle this, since I can't create issues in the Zooniverse fork of this repo.

**Comment by adammcmaster** [comment]
Sure, I’ll set this up tomorrow.

**Comment by adammcmaster** [comment]
Done!

**Comment by willettk** [comment]
Hm - got a 404. Not live yet?

**Comment by adammcmaster** [comment]
Oh... looks like it didn't deploy properly. It should be working in ~10 minutes.

**Comment by willettk** [comment]
Looks good. Thanks, Adam!
